server:
  port: 7000
  servlet:
    context-path: /ad-sponsor

spring:
  application:
    name: client-ad-sponsor
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/ad_sponsor?autoReconnect=true
    username: root
    password: 1234
    tomcat:
      max-active: 6
      min-idle: 3
      initial-size: 3

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/
